name: Remote Dispatch Action Dispatcher

on: [push]

jobs:
  dispatch_action:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch to Scripts repo
        uses: california-energy-commission/Scripts@main
        with:
          access-token: ${{ secrets.CROSS_REPO_ACCESS_TOKEN }}
          github-ref: ${{ github.event.pull_request.head.ref }}
          repository-name: ${{ github.event.repository.name }}
          repository-owner: ${{ github.repository_owner }}
